export const UI_TEXT = {
  badge: {
    module1: 'Module 1',
    module3: 'Module 3',
    module4: 'Module 4',
    calculator: 'Calculator',
    history: 'History',
  },
  nav: {
    home: 'Home',
    newCalculation: 'New Calculation',
    calculationResults: 'Calculation Results',
    savedCalculations: 'Saved Calculations',
    settings: 'Settings',
  },
  actions: {
    calculate: 'Calculate',
    clearInputs: 'Clear Inputs',
    newCalculation: 'New Calculation',
    calculationHistory: 'Calculation History',
    settings: 'Settings',
    viewResults: 'View Results',
    backToHome: 'Back to Home',
  },
  home: {
    title: 'Mechanical Design Calculator',
    description:
      'Calculate motor selection, transmission ratios, and shaft characteristics for Module 1.',
    moduleScopeTitle: 'Module Scope',
    moduleScopeDescription:
      'Module 1 covers motor selection, transmission ratios, and shaft characteristics.',
    moduleScopeBullets: [
      'Enter required power and output speed.',
      'Review the selected motor and required motor power.',
      'Inspect transmission ratios and shaft characteristics.',
    ],
    getStartedTitle: 'Get Started',
    getStartedDescription:
      'Choose an action to start a new calculation or review saved results.',
    recentCalculationTitle: 'Recent Calculation',
    recentCalculationDescription: 'Review the latest saved calculation at a glance.',
    overviewTitle: 'Calculation Overview',
    overviewDescription:
      'Each calculation includes the selected motor, system efficiency, transmission ratios, and shaft characteristics.',
  },
  newCalculation: {
    title: 'New Calculation',
    description:
      'Enter the required values to calculate motor selection and transmission ratios.',
    referenceValuesTitle: 'Reference Values',
    referenceValuesDescription: 'Reference values used in this calculation workflow.',
    requiredInputsTitle: 'Required Inputs',
    requiredInputsDescription: 'Enter the required power and output speed.',
    calculationFlowTitle: 'Calculation Flow',
    calculationFlowDescription:
      'Your inputs are validated and organized into clear result sections.',
    calculationFlowBullets: [
      'Validate required inputs.',
      'Calculate the selected motor.',
      'Distribute transmission ratios.',
      'Display calculation results.',
    ],
    loadingTitle: 'Calculating Results...',
    loadingDescription: 'Processing the required power and output speed.',
    bootstrapLoadingTitle: 'Loading Reference Values',
    bootstrapLoadingDescription: 'Loading the values used in this calculation workflow.',
  },
  fields: {
    powerLabel: 'Power (kW)',
    powerPlaceholder: 'e.g. 1.20',
    powerHelper: 'Required power on the drum shaft.',
    outputSpeedLabel: 'Output Speed (rpm)',
    outputSpeedPlaceholder: 'e.g. 48',
    outputSpeedHelper: 'Required rotational speed at the output shaft.',
    availableMotors: 'Available Motors',
    defaultBeltRatio: 'Default Belt Ratio',
    defaultGearRatio: 'Default Gear Ratio',
    efficiencyD: 'Efficiency (ηD)',
  },
  results: {
    title: 'Calculation Results',
    description:
      'Review the selected motor, system efficiency, transmission ratios, and shaft characteristics.',
    inputSummaryTitle: 'Input Summary',
    inputSummaryDescription: 'Confirmed input values for this calculation.',
    requestId: 'Request ID',
    selectedMotorTitle: 'Selected Motor',
    selectedMotorDescription: 'Motor selected for the required power and speed.',
    motorName: 'Motor Name',
    motorCode: 'Motor Code',
    ratedPower: 'Rated Power (kW)',
    ratedSpeed: 'Rated Speed (rpm)',
    phase: 'Phase',
    systemEfficiencyTitle: 'System Efficiency',
    systemEfficiencyDescription: 'Overall efficiency used for this calculation.',
    systemEfficiencyLabel: 'System Efficiency',
    requiredMotorPowerTitle: 'Required Motor Power',
    requiredMotorPowerDescription: 'Minimum motor power required after efficiency losses.',
    requiredMotorPowerLabel: 'Required Motor Power (kW)',
    transmissionRatiosTitle: 'Transmission Ratios',
    transmissionRatiosDescription: 'Overall and stage transmission ratios.',
    overallRatio: 'Overall Ratio',
    beltU1: 'Belt (U1)',
    bevelGearU2: 'Bevel Gear (U2)',
    spurGearU3: 'Spur Gear (U3)',
    shaftCharacteristicsTitle: 'Shaft Characteristics',
    shaftCharacteristicsDescription: 'Power, speed, and torque for each shaft stage.',
    power: 'Power (kW)',
    speed: 'Speed (rpm)',
    torque: 'Torque (Nmm)',
    outputDrumShaft: 'Output Drum Shaft',
    notesTitle: 'Calculation Notes',
    notesDescription: 'Important messages and display notes for this result.',
    notes: [
      'Values are rounded for display.',
      'Open History to review saved calculations.',
    ],
    noAdditionalNotes: 'No additional notes.',
    roundedDisplayNote: 'Displayed speed values are rounded for readability.',
    noSummary: 'Summary unavailable.',
  },
  history: {
    title: 'Saved Calculations',
    description: 'Review previous calculations and reopen saved results.',
    emptyTitle: 'No calculations yet',
    emptyDescription: 'Start a new calculation to see results here.',
    detailsTitle: 'History Details',
    detailsDescription:
      'Each saved calculation shows a summary, timestamp, and quick access to results.',
    savedIn: 'Saved In',
    savedInValue: 'Calculation History',
    reference: 'Reference',
    referenceValue: 'Request ID',
    availability: 'Availability',
    availabilityValue: 'Latest Results',
    openResults: 'Open Results',
    openResultsValue: 'From History',
    saved: 'Saved',
  },
  settings: {
    title: 'Settings',
    description: 'View app details and display preferences.',
    appInformationTitle: 'App Information',
    appInformationDescription:
      'Version, module, and reference details for this calculator.',
    appName: 'App Name',
    activeModule: 'Active Module',
    calculationMode: 'Calculation Mode',
    calculationModeValue: 'Engineering Calculation',
    dataSource: 'Data Source',
    dataSourceValue: 'Module 1 Service',
    reference: 'Reference',
    referenceValue: 'Module 1 API Contract',
    displayPreferencesTitle: 'Display Preferences',
    displayPreferencesDescription: 'Current defaults used throughout the app.',
    units: 'Units',
    unitsValue: 'Metric',
    numericFormatting: 'Numeric Formatting',
    numericFormattingValue: 'Standard Precision',
    environment: 'Environment',
    environmentValue: 'Default',
    currentScopeTitle: 'Current Scope',
    currentScopeDescription:
      'This release focuses on calculation, review, and history for Module 1.',
    currentScopeBullets: [
      'Module 1 calculation workflow',
      'Saved calculation history',
      'Engineering result review',
    ],
  },
  states: {
    noCalculationResultTitle: 'No calculations yet',
    noCalculationResultDescription:
      'Start a new calculation to see results here.',
    loadingSavedResultsTitle: 'Loading Calculation Results',
    loadingSavedResultsDescription: 'Preparing the latest saved calculation.',
    invalidInput: 'Invalid input',
    invalidInputDescription: 'Please enter a value greater than 0.',
    invalidInputMessage: 'Invalid input. Please enter a value greater than 0.',
    unableToCalculate: 'Unable to calculate. Please check your input.',
    bootstrapError: 'Unable to load reference values.',
    noSuitableMotor: 'No suitable motor was found for the current input values.',
  },
  module3: {
    newTitle: 'Bevel Gear Design',
    newDescription: 'Select material and configure overrides for the straight bevel gear stage.',
    resultTitle: 'Bevel Gear Results',
    resultDescription: 'Review geometry, allowable stresses, and shaft force vectors.',
    materialsTitle: 'Gear Materials',
    materialsDescription: 'Select a material from the available catalog.',
    geometryTitle: 'Gear Geometry',
    geometryDescription: 'Calculated dimensions for the straight bevel gear.',
    stressesTitle: 'Stress Verification',
    stressesDescription: 'Contact and bending stress check results.',
    forcesTitle: 'Shaft Force Vectors',
    forcesDescription: '3D force components acting on the shafts.',
    proceedToBevel: 'Proceed to Bevel Gear Design',
    inputOverridesTitle: 'Input Overrides',
    inputOverridesDescription: 'Optionally override values inherited from Module 1.',
  },
  module3Fields: {
    material: 'Material',
    heatTreatment: 'Heat Treatment',
    hardness: 'Hardness (HB)',
    tensileStrength: 'Tensile Strength (MPa)',
    yieldStrength: 'Yield Strength (MPa)',
    torqueT1: 'Input Torque T1 (Nmm)',
    speedN1: 'Input Speed n1 (rpm)',
    ratioU2: 'Bevel Ratio u2',
    lifeHours: 'Service Life (h)',
    outerConeDistance: 'Outer Cone Distance (Re)',
    pitchDiameter: 'Outer Pitch Diameter (de1)',
    module: 'Outer Module (mte)',
    teethZ1: 'Pinion Teeth (z1)',
    teethZ2: 'Gear Teeth (z2)',
    actualRatio: 'Actual Ratio',
    faceWidth: 'Face Width (b)',
    meanDiameter1: 'Mean Diameter 1 (dm1)',
    meanDiameter2: 'Mean Diameter 2 (dm2)',
    coneAngle1: 'Cone Angle 1 (δ1)',
    coneAngle2: 'Cone Angle 2 (δ2)',
    contactStress: 'Contact Stress (σH)',
    bendingStress1: 'Bending Stress 1 (σF1)',
    bendingStress2: 'Bending Stress 2 (σF2)',
    allowableContact: 'Allowable Contact (σH)',
    allowableBending: 'Allowable Bending (σF)',
    tangentialForce: 'Tangential Force (Ft)',
    radialForce: 'Radial Force (Fr)',
    axialForce: 'Axial Force (Fa)',
    pass: 'PASS',
    fail: 'FAIL',
  },
  module4: {
    newTitle: 'Spur Gear Design',
    newDescription: 'Configure overrides for the straight spur gear stage.',
    resultTitle: 'Spur Gear Results',
    resultDescription: 'Review geometry, derived factors, and stress checks.',
    geometryTitle: 'Spur Gear Geometry',
    geometryDescription: 'Calculated dimensions for the straight spur gear stage.',
    factorsTitle: 'Derived Factors',
    factorsDescription: 'Calculated factors for load distribution and geometry.',
    stressesTitle: 'Stress Verification',
    stressesDescription: 'Contact and bending stress check results.',
    proceedToSpur: 'Proceed to Spur Gear Design',
  },
  module4Fields: {
    torqueT2: 'Input Torque T2 (Nmm)',
    speedN2: 'Input Speed n2 (rpm)',
    ratioU3: 'Spur Ratio u3',
    allowableContact: 'Allowable Contact (σH)',
    allowableBending1: 'Allowable Bending 1 (σF1)',
    allowableBending2: 'Allowable Bending 2 (σF2)',
    centerDistance: 'Center Distance (aw)',
    module: 'Module (m)',
    teethZ1: 'Teeth Gear 1 (z1)',
    teethZ2: 'Teeth Gear 2 (z2)',
    actualRatio: 'Actual Ratio',
    ratioError: 'Ratio Error (%)',
    diameterDw1: 'Pitch Diameter 1 (dw1)',
    diameterDw2: 'Pitch Diameter 2 (dw2)',
    faceWidth: 'Face Width (bw)',
    epsilonAlpha: 'Contact Ratio (εα)',
    zEpsilon: 'Factor Zε',
    yEpsilon: 'Factor Yε',
    yF1: 'Factor YF1',
    yF2: 'Factor YF2',
    loadFactorKh: 'Load Factor KH',
    loadFactorKf: 'Load Factor KF',
    bendingStress1: 'Bending Stress 1 (σF1)',
    bendingStress2: 'Bending Stress 2 (σF2)',
  },
} as const;
